kind: Service
apiVersion: v1
metadata:
  name: recipe-shop-service
spec:
  type: NodePort
  selector:
    app: recipe-shop
  ports:
  - protocol: TCP
    port: 30180
    nodePort: 30180

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: recipe-shop-deployment
  labels:
    app: recipe-shop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: recipe-shop
  template:
    metadata:
      labels:
        app: recipe-shop
    spec:
      containers:
      - name: recipe-shop
        image: $DOCKER_IMAGE_NAME:$BUILD_NUMBER
        ports:
        - containerPort: 8080
